import com.xpdustry.toxopid.spec.ModMetadata
import com.xpdustry.toxopid.spec.ModPlatform

plugins {
  id "java"
  id "com.xpdustry.toxopid" version "4.2.0"
  id "net.kyori.indra.publishing" version "4.0.0"
}

def metadata = ModMetadata.fromJson(file("plugin.hjson"))
group = "com.xpdustry"
version = metadata.version
description = metadata.description

repositories {
  mavenCentral()
  maven { url "https://maven.xpdustry.com/mindustry" }
  maven { url "https://www.jitpack.io" }
}

toxopid {
  compileVersion = "v${metadata.minGameVersion}"
  platforms = [ModPlatform.SERVER]
}

dependencies {
  compileOnly toxopid.dependencies.arcCore
  compileOnly toxopid.dependencies.mindustryCore
  // For SLF4MD compatibility
  compileOnly "org.slf4j:slf4j-api:2.0.18"
}

compileJava {
  targetCompatibility = JavaVersion.VERSION_17
  sourceCompatibility = JavaVersion.VERSION_17
  options.encoding = "UTF-8"
  options.release = 17
}

processResources.from(rootDir) {
    include "plugin.hjson"
  }

jar {
  archiveFileName = "${metadata.name}.jar"

  //copy the builded jar to the working directory
  doLast {
		copy {
			from jar
			into rootDir
		}
	}
}

// Publishing
signing {
  def signingKey = findProperty("signingKey")
  def signingPassword = findProperty("signingPassword")
  useInMemoryPgpKeys(signingKey, signingPassword)
}

indra {
  javaVersions {
    target(17)
    minimumToolchain(17)
  }
    
  mitLicense()
  publishReleasesTo("xpdustry", "https://maven.xpdustry.com/releases")

  def repo = metadata.repository.split("/")
  github(repo[0], repo[1]) {
    ci(true)
    issues(true)
    scm(true)
  }

  configurePublications {
    from components.java
    artifact sourcesJar
    artifact javadocJar
  
    pom {
      organization {
        name = "Xpdustry"
        url = "https://www.xpdustry.com"
      }

      developers {
        metadata.author.split(",").each { a ->
          developer {
            id = a.trim()
            url = "https://github.com/${id.get()}"
          }
        }
      }
    }
  }
}

// I want these to only be included when publishing, not all the time...
task javadocJar(type: Jar, dependsOn: 'javadoc') {
    from javadoc.destinationDir
    archiveClassifier = 'javadoc'
}
task sourcesJar(type: Jar, dependsOn: 'classes') {
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
}
